global:
  scrape_interval: 10s

scrape_configs:          
  - job_name: 'sunrise-server'
    static_configs:
      - targets: [ 'host.docker.internal:5147' ]
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']