global:
  scrape_interval: 10s

scrape_configs:
  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]
  - job_name: "sunrise-server"
    static_configs:
      - targets: ["sunrise-server:5147"]
